#!/bin/bash
#
# Anthony Rutledge
# anthony_rutledge_101@yahoo.com
# https://www.linkedin.com/in/anthony-rutledge-2988b0125/

function fileHas ()
{
    pattern=$1
    inputFile=$2

    grep -q $pattern $inputFile &> /dev/null
}

function getLine ()
{
    pattern=$1
    inputFile=$2

    if [[ ! fileHas $pattern $inputFile ]]
    then
        return 1
    fi

    grep $pattern $inputFile | head -n 1
}

function lineMatchCount ()
{
    grep -c $pattern $inputFile
}

function getLineCount ()
{
    filename=$1
    trim $(wc -l $filename | awk {'print $1'})
}

function getNumberedLine ()
{
    pattern=$1
    inputFile=$2

    grep -n -m 1 $pattern $inputFile
}

function getLineNumber ()
{
    pattern=$1
    inputFile=$2

    getNumberedLine $pattern $inputFile | awk -F : {'print $1'}
}

function selectLines ()
{
    startLineNumber=$1
    endLineNumber=$2
    inputFile=$3

    sed -n "${startLineNumber},${endLineNumber}p" $inputFile
}

function getLineRangeToPattern ()
{
    startLineNumber=$1
    endLinePattern=$2
    inputFile=$3

    sed -n "${startLineNumber},/${endLinePattern}/p" $inputFile 
}

function getLineRange ()
{
    pattern1=$1
    pattern2=$2
    inputFile=$3

    startLineNumber=$(getLineNumber $pattern1 $inputFile)
    endLineNumber=$(getLineNumber $pattern2 $inputFile)
    selectLines $startLineNumber $endLineNumber $inputFile
}

function insertAbove ()
{
    targetLineNumber=$1
    newLine=$2
    inputFile=$3

    sed -i "${targetLineNumber}i${newLine}" $inputFile
}

function insertBelow ()
{
    targetLineNumber=$1
    newLine=$2
    inputFile=$3

    sed -i "${targetLineNumber}a${newLine}" $inputFile
}

function updateRecord ()
{
    targetLineNumber=$1
    searchString=$2
    substitution=$3
    inputFile=$4

    sed -i "${targetLineNumber}s/${searchString}/${substitution}/" $inputFile
}

function overwrite ()
{
    targetLineNumber=$1
    replacementLine=$2
    inputFile=$3

    sed -i "${targetLineNumber}c${replacementLine}" $inputFile
}

function deleteRecord ()
{
    targetLineNumber=$1
    inputFile=$2

    sed -i "${targetLineNumber}d" $inputFile
}

function getColumn ()
{
    delimiter=$1
    field=$2
    inputFile=$3

    cut -d $1 -f $2 -s $inputFile
}
